name: CD

on:
  push:
    branches:
      - master2

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull poojajeeva/test:latest

      - name: Start Docker containerpoojajeeva/test:latest
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 poojajeeva/test:latest)
          echo "::set-output name=container_id::$container_id"

          docker ps -a
          
      - name: Check Container Logs
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          docker logs $container_id
      
      - name: Check if Container is Running
        id: check-container
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          container_status=$(docker inspect -f '{{.State.Running}}' $container_id)
          if [ "$container_status" == "true" ]; then
          echo "Container is running"
          echo "::set-output name=container_running::true"
          else
          echo "Container is not running"
          echo "::set-output name=container_running::false"
          fi
      - name: Check JAR file in Docker container
        run: |
           container_id=$(docker ps -q)  # Get the container ID
           docker exec $container_id find /app -name "JtSpringProject-0.0.1-SNAPSHOT.jar"
      - name: Access the container
        run: |
          host_port=${{ steps.get-port.outputs.host_port }}
          echo "Accessing application at http://localhost:$host_port"
           
      - name: Get Container IP address
        id: get-container-ip
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
          echo "::set-output name=container_ip::$container_ip"

      - name: Use Container IP address
        run: |
         container_ip=${{ needs.get-container-ip.outputs.container_ip }}
         echo "Container IP address: $container_ip"
    # Use the container_ip in your subsequent steps to access the container
    
      - name: Inspect Docker container
        id: inspect-container
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
          echo "::set-output name=container_ip::$container_ip"

      - name: Access the container
        run: |
          container_ip=${{ needs.inspect-container.outputs.container_ip }}
          # Use the container_ip in your subsequent steps to access the container
          echo "Container IP address: $container_ip"
