name: CD

on:
  push:
    branches:
      - master2

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull poojajeeva/test:latest

      - name: Start Docker containerpoojajeeva/test:latest
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 poojajeeva/test:latest)
          echo "::set-output name=container_id::$container_id"

          docker ps -a
          
      - name: Check Container Logs
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          docker logs $container_id
      
      - name: Check if Container is Running
        id: check-container
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          container_status=$(docker inspect -f '{{.State.Running}}' $container_id)
          if [ "$container_status" == "true" ]; then
          echo "Container is running"
          echo "::set-output name=container_running::true"
          else
          echo "Container is not running"
          echo "::set-output name=container_running::false"
          fi
      - name: Check JAR file in Docker container
        run: |
           container_id=$(docker ps -q)  # Get the container ID
           docker exec $container_id find /app -name "JtSpringProject-0.0.1-SNAPSHOT.jar"
